---
- name: Play that as outer and inner loops
  hosts: localhost
  tasks:
    - include_tasks: tasks/loop_task.yml
      loop:
        - alex
        - bob
        - john
      loop_control:
        loop_var: other_info